@startuml

class Harmony {
    Set<NoteName> components
    + boolean fit(Pitch)
}

enum Scale {
    MAJOR_SCALE
    MINOR_PENTATONIC_SCALE
    + PitchInterval[] intervals()
}

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml