package music.analysis.feature.name;

public enum RuleName implements MelodicFeatureName {
    PERFECT_CONSONANCE, IMPERFECT_CONSONANCE, DIATONIC_NOTE, LESS_THAN_OCTAVE,
    HALF_NOTE, QUARTER_NOTE, EIGHT_NOTE, SIXTEENTH_NOTE,
    ONE_LINED_GRAVITY,
    SCALE_NOTE, CHORD_NOTE, REST_NOTE, STRONG_BEAT
}
