package music.analysis.feature.name;

public enum StatisticName implements MelodicFeatureName {
    PITCH_VARIETY, DISSONANCE_RATING, RHYTHM_VARIETY, RHYTHM_RANGE, NON_SCALE_RATING, PITCH_RANGE, MAJOR_OR_MINOR_SECOND_RATING,
    CONTOUR_DIRECTION, CONTOUR_STABILITY, REST_DENSITY, REPEATED_INTERVALS, REPEATED_RHYTHM_INTERVALS,
    ILLEGAL_JUMP, CHORD_NOTES, AVERAGE_PITCH, PITCH_STANDARD_DEVIATION, STRONG_BEAT, AVERAGE_RHYTHM,
    RHYTHM_STANDARD_DEVIATION
}
