package music.analysis.feature.name;

public enum StatisticName implements MelodicFeatureName {
    PITCH_VARIETY, DISSONANCE_RATING, RHYTHM_VARIETY, RHYTHM_RANGE, NON_SCALE_RATING, PITCH_RANGE, DIATONIC_RATING,
    CONTOUR_DIRECTION, CONTOUR_STABILITY, REST_DENSITY, REPEATED_INTERVALS, REPEATED_RHYTHM_INTERVALS,
    OCTAVE_DIFFERENCE, SEMITONES_DIFFERENCE, CHORD_NOTES, AVERAGE_PITCH
}
